# Generated by Django 4.1.5 on 2023-01-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TreeViewMenu', '0002_remove_treemenu_url_treemenu_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treemenu',
            options={'ordering': ['parent'], 'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.RemoveField(
            model_name='treemenu',
            name='position',
        ),
        migrations.AddField(
            model_name='treemenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='TreeViewMenu.treemenu'),
        ),
    ]
