# Generated by Django 4.1.5 on 2023-01-24 16:09

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TreeViewMenu', '0003_alter_treemenu_options_remove_treemenu_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treemenu',
            options={'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.AlterField(
            model_name='treemenu',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='TreeViewMenu.treemenu'),
        ),
    ]
