# Generated by Django 4.1.5 on 2023-01-24 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TreeViewMenu', '0005_treemenu_mptt_delete_treemenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeMenu_native',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='slug')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TreeViewMenu.treemenu_native')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
