# Generated by Django 4.1.5 on 2023-01-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TreeViewMenu', '0006_treemenu_native'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treemenu_mptt',
            options={'verbose_name': 'Пункт меню', 'verbose_name_plural': 'MPTT'},
        ),
        migrations.AlterModelOptions(
            name='treemenu_native',
            options={'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Native'},
        ),
    ]
