# Generated by Django 4.1.5 on 2023-01-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TreeViewMenu', '0007_alter_treemenu_mptt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemenu_native',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TreeViewMenu.treemenu_native'),
        ),
    ]
