# Generated by Django 4.1.5 on 2023-01-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeViewMenu', '0009_alter_treemenu_native_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treemenu_native',
            options={'ordering': ['position'], 'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Native'},
        ),
        migrations.AddField(
            model_name='treemenu_native',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Позиция'),
        ),
    ]
