# Generated by Django 4.1.5 on 2023-01-24 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TreeViewMenu', '0010_alter_treemenu_native_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreeMenu_native',
        ),
    ]
